[WIP] load an excerpt of an csv into datastore
opendata-swiss/ckanext-xloader pull request #3
Opened 2018-11-13 16:38 UTC by stefina

This is my very rookie and WIP approach to make it possible to load only a part of a csv into the datastore.

This will kick in if either the file is bigger than the max_content_length and try to upload the first few configured number of rows.

It is lacking tests as this is so far a POC to discuss if this is beneficial and how this should be configured (the logic is not yet desirable)

2018-11-14 15:48 UTC, metaodi requested changes
As discuss consider to add a new `FileTooBigError` and catch this error to try adding the excerpt. If the option is not set or the excepert generation fails, you can then raise a `JobError` from your new code.

2018-11-14 15:48 UTC, metaodi commented on ckanext/xloader/jobs.py
> +            else:
this else is unnecessary, remove it and un-indent the block

2018-11-14 15:48 UTC, metaodi commented on ckanext/xloader/jobs.py
> +                               'loading bigger files partially to DataStore.')
I personally would remove this warning message. It clutters the log with not very useful information.

2018-11-14 15:48 UTC, metaodi commented on ckanext/xloader/jobs.py
> +                    m.update(tmp_file.read())
move this whole block further down, when you really know if the file is too big.

2019-02-19 09:20 UTC, stefina commented
Closing this as this is a duplicate to https://github.com/ckan/ckanext-xloader/pull/63

2019-02-19 09:20 UTC, closed without merging